background {
    monitor =
    path = ~/.config/hypr/Backgrounds/image-4.png
    color = $background
    blur_passes = 2
    contrast = 1
    brightness = 0.7
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.3
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(153, 153, 153, 1)
    inner_color = rgba(00000000)
    font_color = rgba(153, 153, 153, 1)
    fade_on_empty = false
    rounding = 1
    placeholder_text = $USER
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor = 
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(153, 153, 153, 1)
    font_size = 128
    font_family = JetBrains Mono Extrabold
    position = 0, 100
    halign = center
    valign = center
}